DROP SEQUENCE BILLSEQ;
DROP TABLE BILL;

CREATE SEQUENCE BILLSEQ;

CREATE TABLE BILL(
	BILL_NUM NUMBER PRIMARY KEY,
	BILL_NAME VARCHAR2(2000) NOT NULL,
	BILL_PRICE NUMBER NOT NULL,
	BILL_QUANTITY NUMBER NOT NULL,
	BILL_TOTAL NUMBER NOT NULL,
	BILL_DATE VARCHAR2(1000) NOT NULL,
	MEMBER_ID VARCHAR2(500) NOT NULL
);

SELECT BILL_NUM, BILL_NAME, BILL_PRICE, BILL_QUANTITY, BILL_TOTAL, BILL_DATE, MEMBER_ID
FROM BILL
ORDER BY BILL_NUM DESC;

INSERT INTO BILL
VALUES(BILLSEQ.NEXTVAL, '사과', 2200, 1, 2200, '2021-07-02', 'asd123');

