
CREATE SEQUENCE BRNUMSEQ;
DROP SEQUENCE BRNUMSEQ;


CREATE TABLE BOARDRECIPE (
	BR_NUM	NUMBER		PRIMARY KEY,
	BR_TITLE	VARCHAR2(1000)		NOT NULL,
	BR_CONTENT	VARCHAR2(4000)		NOT NULL,
	BR_REGDATE	DATE		NOT NULL,
	BR_READCOUNT	NUMBER	DEFAULT 0	NOT NULL,
	BR_RECCOUNT	NUMBER	DEFAULT 0	NOT NULL,
	BR_CATEGORY	VARCHAR2(500)		NULL,
	MEMBER_ID	VARCHAR2(500)		NOT NULL
);

ALTER TABLE BOARDRECIPE ADD (CONSTRAINT FK_MEMBER_ID) FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID);


DROP TABLE BOARDRECIPE;

DELETE FROM BOARDRECIPE;

SELECT * FROM BOARDRECIPE;

INSERT INTO BOARDRECIPE VALUES(BRNUMSEQ.NEXTVAL,'페이징테스트','페이징 테스트중입니다.',SYSDATE,0,0,'Board','테스트');

	SELECT BR_NUM, BR_TITLE, BR_CONTENT, BR_REGDATE, BR_READCOUNT,BR_RECCOUNT,BR_DELFLAG,BR_CATEGORY,MEMBER_ID
	FROM BOARDRECIPE
	ORDER BY BR_NUM DESC;
	
	select * from all_all_tables;

	select * from tabs;
	select * from member;
	

	SELECT *
		FROM (
		SELECT ROWNUM
		RN, A.*
		FROM (
		SELECT *
		FROM BOARDRECIPE
		ORDER BY BR_NUM DESC
		) A
		)
		WHERE BR_TITLE like '%1%';
	