DROP TABLE CLASS;
DROP SEQUENCE CLASS_NUM;

CREATE SEQUENCE CLASS_NUM;
CREATE TABLE CLASS(
	CLASS_NUM NUMBER,
	TEACHER_ID VARCHAR2(100) NOT NULL PRIMARY KEY,
	CLASS_TITLE VARCHAR2(200) NOT NULL,
	CLASS_INTRO VARCHAR2(3000) NOT NULL,
	CLASS_PRICE NUMBER NOT NULL,
	CLASS_HOW VARCHAR2(50) NOT NULL,
	CLASS_WHERE VARCHAR2(1000) DEFAULT '온라인 강의입니다.',
	CLASS_INGRED VARCHAR2(2000) NOT NULL,
	CLASS_CONTENT VARCHAR2(3000) NOT NULL,
	CLASS_REGDATE DATE NOT NULL,
	CLASS_MEDIA_PATH VARCHAR2(300),
	CONSTRAINT FK_MEMBERID FOREIGN KEY(TEACHER_ID)
	REFERENCES MEMBER(MEMBER_ID),
	CONSTRAINT CLASS_HOW_CHK CHECK (CLASS_HOW IN ('N', 'F'))
);

SELECT * FROM CLASS;