DROP SEQUENCE LECTURESEQ;
DROP TABLE LECTURE;

CREATE SEQUENCE LECTURESEQ;

CREATE TABLE LECTURE(
	LECTURE_NUM NUMBER PRIMARY KEY,
	LECTURE_NAME VARCHAR2(1000) NOT NULL,
	MEMBER_ID VARCHAR2(500) NOT NULL,
	MEMBER_NAME VARCHAR2(200) NOT NULL,
	LECTURE_CATEGORY VARCHAR2(500) NOT NULL,
	LECTURE_PRICE NUMBER NOT NULL,
	LECTURE_CONTENT VARCHAR2(4000) NOT NULL
);

SELECT LECTURE_NUM, LECTURE_NAME, MEMBER_ID, MEMBER_NAME, LECTURE_CATEGORY, LECTURE_PRICE, LECTURE_CONTENT
FROM LECTURE
ORDER BY LECTURE_NUM DESC;

SELECT * FROM LECTURE;

INSERT INTO LECTURE
VALUES(LECTURESEQ.NEXTVAL, '일식 패키지', '123', '강사2', '일식', '39800', '일식을 배울 수 있습니다');

UPDATE LECTURE
SET MEMBER_ID = 12
WHERE LECTURE_NUM = 1;

DELETE FROM LECTURE 
WHERE LECTURE_NUM = 22;
