DROP SEQUENCE PAYSEQ;
DROP TABLE PAY;

CREATE SEQUENCE PAYSEQ;

CREATE TABLE PAY(
	PAY_NUM NUMBER PRIMARY KEY,
	PAY_DATE DATE NOT NULL,
	PAY_PRICE NUMBER NOT NULL,
	PAY_STEP VARCHAR2(500) NOT NULL,
	MEMBER_ID VARCHAR2(500) NOT NULL,
	LECTURE_NUM NUMBER NOT NULL,
	LECTURE_NAME VARCHAR2(1000) NOT NULL,
	LECTURE_CATEGORY VARCHAR2(500) NOT NULL
);

SELECT PAY_NUM, PAY_DATE, PAY_PRICE, PAY_STEP, MEMBER_ID, LECTURE_NUM, LECTURE_NAME, LECTURE_CATEGORY
FROM PAY
ORDER BY PAY_NUM DESC;

INSERT INTO PAY
VALUES(PAYSEQ.NEXTVAL, SYSDATE, '39800', '결제완료', 'asd123', 41, '일식 패키지', '일식');

UPDATE PAY
SET LECTURE_NAME = '한식 패키지2'
WHERE PAY_NUM = 1;

SELECT P.PAY_NUM, P.PAY_DATE, C.CLASS_PRICE, P.PAY_STEP, P.MEMBER_ID, C.CLASS_NUM, C.CLASS_TITLE, 
(SELECT MEMBER_CATEGORY FROM MEMBER WHERE MEMBER_ID = C.TEACHER_ID) AS CLASS_CATEGORY
FROM PAY P, CLASS C
WHERE P.MEMBER_ID = 'asd123';


