
SELECT MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_EMAIL, MEMBER_PHONE, MEMBER_ADDRESS, MEMBER_ROLE, MEMBER_CATEGORY, MEMBER_CERTI, MEMBER_CAREER, MEMBER_REGDATE
FROM MEMBER
ORDER BY MEMBER_ID DESC;

INSERT INTO MEMBER
VALUES('asd123', 'asd123', '학생1', '1234@123', '010-123-1456', '서울, 어딘가', 'M', NULL, NULL, NULL, SYSDATE);

DELETE FROM MEMBER
WHERE MEMBER_ID = '12';

UPDATE MEMBER
SET MEMBER_ADDRESS = '서울 강남구,12,345,678'
WHERE MEMBER_ID = '12';

SELECT FOOD_NUM, FOOD_NAME, FOOD_LIFE, FOOD_ALARM_YN, MEMBER_ID 
FROM FOOD
WHERE MEMBER_ID = 'asd123';















